V4.11.1.30#4
More Linux changes
Installation process
Plug-in related fixes

diff --git a/PackageFiles/MiscellaneousLinux/DEBIAN/postinst b/PackageFiles/MiscellaneousLinux/DEBIAN/postinst
--- a/PackageFiles/MiscellaneousLinux/DEBIAN/postinst
+++ b/PackageFiles/MiscellaneousLinux/DEBIAN/postinst
@@ -1,5 +1,6 @@
 #!/bin/bash
 set -e
+
 # Automatically added by dh_installdocs
 if [ "$1" = "configure" ]; then
   if [ -d /usr/doc -a ! -e /usr/doc/parted -a -d /usr/share/doc/parted ]; then
@@ -27,33 +28,22 @@ installUSBHardware() {
 #  Eclipse Plugin Installation
 #======================================================
 # $1 - Eclipse directory
-# $2 - USBDM plugin directory
+# $2 - Feature Group
 #
 installEclipsePlugins() {
 
-   local ECLIPSE_DIR="$1"
-   local ECLIPSE_DROPIN_DIR="${ECLIPSE_DIR}/dropins"
-   local USBDM_PLUGIN_DIR="$2"
+   P2_APPLICATION="org.eclipse.equinox.p2.director"
 
-   if [[ ! -d ${ECLIPSE_DROPIN_DIR} ]]; then
-      echo " Dropin directory ${ECLIPSE_DROPIN_DIR} Not Found"
-      return
-   fi
+   local ECLIPSE_DIR="$1"
+   local FEATURE_GROUP="$2"
 
    echo 
-   echo "Installing Eclipse CDT plugins to ${ECLIPSE_DROPIN_DIR}"
+   echo "Installing Eclipse CDT plugins to ${ECLIPSE_DIR}"
    echo "=================================================================="
-   if [[ -d "${ECLIPSE_DROPIN_DIR}/usbdm" ]]; then
-      rm -rfv "${ECLIPSE_DROPIN_DIR}/usbdm"
-   fi
-   mkdir -pv "${ECLIPSE_DROPIN_DIR}/usbdm"
-   ln -sv  ${USBDM_PLUGIN_DIR}/* "${ECLIPSE_DROPIN_DIR}/usbdm"
-   
-   echo "Refreshing Eclipse"
    for FILENAME in cwide eclipse; do
       if [[ -x "${ECLIPSE_DIR}/${FILENAME}" ]]; then
-         echo "${ECLIPSE_DIR}/${FILENAME} -clean -initialize -noSplash"
-         ${ECLIPSE_DIR}/${FILENAME} -clean -initialize -noSplash
+         echo ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -repository file:/${USBDM_UPDATE_SITE} -installIU ${FEATURE_GROUP}
+         ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -repository file:/${USBDM_UPDATE_SITE} -installIU ${FEATURE_GROUP} || true
       fi
    done
 }
@@ -72,7 +62,7 @@ installEclipse() {
       echo -n "Looking for Eclipse in '${ECLIPSE_DIR}'"
       if [[ -d ${ECLIPSE_DIR} ]]; then
          echo " - Found"
-         installEclipsePlugins ${ECLIPSE_DIR} ${USBDM_CDT_PLUGINS_DIR}
+         installEclipsePlugins ${ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
       else
         echo " - Not Found"
       fi
@@ -89,21 +79,22 @@ installKDSInstance() {
    local KDS_ECLIPSE_DIR="${KDS_DIR}/eclipse"
    local KDS_PE_DIR="${KDS_ECLIPSE_DIR}/ProcessorExpert/Config/Compiler"
    local KDS_PR_XLKR_FILENAME="net.sourceforge.usbdm.cdt.arm.toolchain.c.compiler.xlkr"
-   local KDS_NANO_SPECS_FILENAME="nano.specs"
+   #local KDS_NANO_SPECS_FILENAME="nano.specs"
    
    # Add USBDM plugins to eclipse
-   installEclipsePlugins ${KDS_ECLIPSE_DIR} ${USBDM_CDT_PLUGINS_DIR}
+   installEclipsePlugins ${KDS_ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
 
    # Add Toolchain nano.specs files
-   local SOURCE="${USBDM_SHARED_DIR}/${KDS_NANO_SPECS_FILENAME}"
-   local DESTINATION="${KDS_TOOLCHAIN_LIB_DIR}/${KDS_NANO_SPECS_FILENAME}"
+   # KDS now used the OS GNU tools - not their own version
+   #local SOURCE="${USBDM_SHARED_DIR}/${KDS_NANO_SPECS_FILENAME}"
+   #local DESTINATION="${KDS_TOOLCHAIN_LIB_DIR}/${KDS_NANO_SPECS_FILENAME}"
    
-   echo Installing nano.specs files...
-   if [[ -d ${KDS_TOOLCHAIN_LIB_DIR} ]]; then
-      ln -svf ${SOURCE} ${DESTINATION}
-   else
-     echo " Toolchain directory '${KDS_TOOLCHAIN_LIB_DIR}' - Not Found"
-   fi
+   #echo Installing nano.specs files...
+   #if [[ -d ${KDS_TOOLCHAIN_LIB_DIR} ]]; then
+   #   ln -svf ${SOURCE} ${DESTINATION}
+   #else
+   #  echo " Toolchain directory '${KDS_TOOLCHAIN_LIB_DIR}' - Not Found"
+   #fi
 
    # Add PE files
    local SOURCE="${USBDM_SHARED_DIR}/${KDS_PR_XLKR_FILENAME}"
@@ -163,16 +154,17 @@ installCodewarriorInstance() {
    WIZARD_DIRECTORY="${CODEWARRIOR_DIR}/MCU/lib/wizard_data"
    ECLIPSE_CWIDE="${CODEWARRIOR_DIR}/eclipse/cwide"
 
-   CF_GDI_TARGETS="usbdm-cfv1-gdi.so usbdm-cfvx-gdi.so usbdm-cfv1-gdi-debug.so usbdm-cfvx-gdi-debug.so"
-   HCS_GDI_TARGETS="usbdm-hcs08-gdi.so usbdm-rs08-gdi.so usbdm-hcs08-gdi-debug.so usbdm-rs08-gdi-debug.so"
-   S12Z_GDI_TARGETS="usbdm-s12z-gdi.so usbdm-s12z-gdi-debug.so"
-   ARM_GDI_TARGETS="usbdm-arm-gdi.so usbdm-arm-gdi-debug.so"
-   DSC_GDI_TARGETS="usbdm-dsc-gdi.so usbdm-dsc-gdi-debug.so"
+   CF_GDI_TARGETS="libusbdm-gdi-cfv1.so libusbdm-gdi-cfvx.so libusbdm-gdi-cfv1-debug.so libusbdm-gdi-cfvx-debug.so"
+   HCS_GDI_TARGETS="libusbdm-gdi-hcs08.so libusbdm-gdi-rs08.so libusbdm-gdi-hcs08-debug.so libusbdm-gdi-rs08-debug.so"
+   S12Z_GDI_TARGETS="libusbdm-gdi-s12z.so libusbdm-gdi-s12z-debug.so"
+   ARM_GDI_TARGETS="libusbdm-gdi-arm.so libusbdm-gdi-arm-debug.so"
+   DSC_GDI_TARGETS="libusbdm-gdi-dsc.so libusbdm-gdi-dsc-debug.so"
 
    echo
    echo "Installing CFV1 & CFVx GDI files to '${CF_GDI_DIRECTORY}'"
    echo "=================================================================="
    for FILENAME in ${CF_GDI_TARGETS}; do
+      echo "Linking ..."
       local SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
       local DESTINATION="${CF_GDI_DIRECTORY}/${FILENAME}"
       ln -svf ${SOURCE} ${DESTINATION}
@@ -241,10 +233,12 @@ installCodewarriorInstance() {
    WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.changewizard_"  
    ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml ${WIZARD_PATCH_FILE}
 
+   echo 
+   echo "Refreshing Eclipse"
    echo touch ${WIZARD_BASE_DIR}\*
    touch ${WIZARD_BASE_DIR}*
 
-   installEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}" ${USBDM_CW_PLUGINS_DIR}
+   installEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}" ${CW_FEATURE_GROUP}
 }
 
 #======================================================
@@ -275,15 +269,17 @@ libraryUpdate() {
       return
    fi 
 
-#   ldconfig ${USBDM_LIB_DIR}
+   echo ldconfig ${USBDM_LIB_DIR}
+   ldconfig ${USBDM_LIB_DIR}
 }
 
 #================================
 # USBDM Version
 #
 MAJOR=4
-MINOR=10
+MINOR=11
 VERSION=${MAJOR}.${MINOR}
+CP_OPTIONS=-p
 
 # Where to find files (relative to /)
 DUMMY_ROOT=""
@@ -299,10 +295,12 @@ else
 fi 
 
 USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
-USBDM_CDT_PLUGINS_DIR="${USBDM_SHARED_DIR}/CDT_Plugins"
-USBDM_CW_PLUGINS_DIR="${USBDM_SHARED_DIR}/CW_Plugins"
+USBDM_UPDATE_SITE="${USBDM_SHARED_DIR}/UpdateSite"
 USBDM_CW_LAUNCH_CONFIG_DIR="${USBDM_SHARED_DIR}/LaunchConfig"
 USBDM_CW_WIZARD_PATCH_DIR="${USBDM_SHARED_DIR}/WizardPatches"
+
+CDT_FEATURE_GROUP="net.sourceforge.usbdm.cdt.feature.feature.group"
+CW_FEATURE_GROUP="net.sourceforge.usbdm.cw.feature.feature.group"
 
 # System directories
 LIB_DIR="/usr/lib"
@@ -313,5 +311,5 @@ installUSBHardware
 installEclipse
 installKDS
 installCodewarrior
-libraryUpdate
+#libraryUpdate $1
 
diff --git a/PackageFiles/MiscellaneousLinux/DEBIAN/prerm b/PackageFiles/MiscellaneousLinux/DEBIAN/prerm
--- a/PackageFiles/MiscellaneousLinux/DEBIAN/prerm
+++ b/PackageFiles/MiscellaneousLinux/DEBIAN/prerm
@@ -1,5 +1,6 @@
 #!/bin/bash
 set -e
+
 # Automatically added by dh_installdocs
 if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then
   rm -fv /usr/doc/parted
@@ -9,7 +10,7 @@ fi
 #======================================================
 #  USB Hardware Removal
 #======================================================
-uninstallUSBHardware() {
+removeUSBHardware() {
 
    echo
    echo "Removing rules file from ${RULES_DIR}"
@@ -21,29 +22,22 @@ uninstallUSBHardware() {
 #  Eclipse Plugin Removal
 #======================================================
 # $1 - Eclipse directory
+# $2 - Feature Group
 #
-uninstallEclipsePlugins() {
+removeEclipsePlugins() {
+
+   P2_APPLICATION="org.eclipse.equinox.p2.director"
 
    local ECLIPSE_DIR="$1"
-   local ECLIPSE_DROPIN_DIR="${ECLIPSE_DIR}/dropins"
-
-   if [[ ! -d ${ECLIPSE_DROPIN_DIR} ]]; then
-      echo " Dropin directory ${ECLIPSE_DROPIN_DIR} Not Found"
-      return
-   fi
+   local FEATURE_GROUP="$2"
 
    echo 
-   echo "Removing Eclipse CDT plugins from ${ECLIPSE_DROPIN_DIR}"
+   echo "Removing Eclipse CDT plugins from ${ECLIPSE_DIR}"
    echo "=================================================================="
-   if [[ -d "${ECLIPSE_DROPIN_DIR}/usbdm" ]]; then
-      rm -rfv "${ECLIPSE_DROPIN_DIR}/usbdm"
-   fi
-
-   echo "Refreshing Eclipse"
    for FILENAME in cwide eclipse; do
       if [[ -x "${ECLIPSE_DIR}/${FILENAME}" ]]; then
-         echo "${ECLIPSE_DIR}/${FILENAME} -clean -initialize -noSplash"
-         ${ECLIPSE_DIR}/${FILENAME} -clean -initialize -noSplash
+         echo ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -uninstallIU ${FEATURE_GROUP}
+         ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -uninstallIU ${FEATURE_GROUP} || true
       fi
    done
 }
@@ -51,7 +45,7 @@ uninstallEclipsePlugins() {
 #======================================================
 #  Eclipse Removal
 #======================================================
-uninstallEclipse() {
+removeEclipse() {
 
    local ECLIPSE_DIR_LIST="/usr/local/eclipse* /opt/eclipse* /usr/lib/eclipse*"
 
@@ -62,7 +56,7 @@ uninstallEclipse() {
       echo -n "Looking for Eclipse in '${ECLIPSE_DIR}'"
       if [[ -d ${ECLIPSE_DIR} ]]; then
          echo " - Found"
-         uninstallEclipsePlugins ${ECLIPSE_DIR}
+         removeEclipsePlugins ${ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
       else
         echo " - Not Found"
       fi
@@ -72,27 +66,28 @@ uninstallEclipse() {
 #======================================================
 #  KDS Instance Removal
 #======================================================
-uninstallKDSInstance() {
+removeKDSInstance() {
 
    local KDS_DIR="$1"
    local KDS_TOOLCHAIN_LIB_DIR="${KDS_DIR}/toolchain/arm-none-eabi/lib"
    local KDS_ECLIPSE_DIR="${KDS_DIR}/eclipse"
    local KDS_PE_DIR="${KDS_ECLIPSE_DIR}/ProcessorExpert/Config/Compiler"
    local KDS_PR_XLKR_FILENAME="net.sourceforge.usbdm.cdt.arm.toolchain.c.compiler.xlkr"
-   local KDS_NANO_SPECS_FILENAME="nano.specs"
+   #local KDS_NANO_SPECS_FILENAME="nano.specs"
    
    # Remove USBDM plugins to eclipse
-   uninstallEclipsePlugins ${KDS_ECLIPSE_DIR}
+   removeEclipsePlugins ${KDS_ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
 
    # Add Toolchain nano.specs files
-   local DESTINATION="${KDS_TOOLCHAIN_LIB_DIR}/${KDS_NANO_SPECS_FILENAME}"
+   # KDS now used the OS GNU tools - not their own version
+   #local DESTINATION="${KDS_TOOLCHAIN_LIB_DIR}/${KDS_NANO_SPECS_FILENAME}"
    
-   echo Removing nano.specs files...
-   if [[ -f ${DESTINATION} ]]; then
-      rm -fv ${DESTINATION}
-   else
-     echo " Specs file '${DESTINATION}' - Not Found"
-   fi
+   #echo Removing nano.specs files...
+   #if [[ -f ${DESTINATION} ]]; then
+   #   rm -fv ${DESTINATION}
+   #else
+   #  echo " Specs file '${DESTINATION}' - Not Found"
+   #fi
 
    # Remove PE files
    local DESTINATION="${KDS_PE_DIR}/${KDS_PR_XLKR_FILENAME}"
@@ -108,7 +103,7 @@ uninstallKDSInstance() {
 #======================================================
 #  KDS Removal
 #======================================================
-uninstallKDS() {
+removeKDS() {
 
    local KDS_DIR_LIST="/usr/local/Freescale/KDS_* /opt/Freescale/KDS_*"
 
@@ -119,7 +114,7 @@ uninstallKDS() {
       echo -n "Looking for Freescale KDS in '${KDS_DIR}'"
       if [[ -d ${KDS_DIR} ]]; then
          echo " - Found"
-         uninstallKDSInstance ${KDS_DIR}
+         removeKDSInstance ${KDS_DIR}
       else
          echo " - Not Found"
       fi
@@ -129,7 +124,7 @@ uninstallKDS() {
 #======================================================
 #  Codewarrior Instance Removal
 #======================================================
-uninstallCodewarriorInstance() {
+removeCodewarriorInstance() {
 
    local CODEWARRIOR_DIR="$1"
    local CODEWARRIOR_ECLIPSE_DIR="$1/eclipse"
@@ -151,11 +146,11 @@ uninstallCodewarriorInstance() {
    WIZARD_DIRECTORY="${CODEWARRIOR_DIR}/MCU/lib/wizard_data"
    ECLIPSE_CWIDE="${CODEWARRIOR_DIR}/eclipse/cwide"
 
-   CF_GDI_TARGETS="usbdm-cfv1-gdi.so usbdm-cfvx-gdi.so usbdm-cfv1-gdi-debug.so usbdm-cfvx-gdi-debug.so"
-   HCS_GDI_TARGETS="usbdm-hcs08-gdi.so usbdm-rs08-gdi.so usbdm-hcs08-gdi-debug.so usbdm-rs08-gdi-debug.so"
-   S12Z_GDI_TARGETS="usbdm-s12z-gdi.so usbdm-s12z-gdi-debug.so"
-   ARM_GDI_TARGETS="usbdm-arm-gdi.so usbdm-arm-gdi-debug.so"
-   DSC_GDI_TARGETS="usbdm-dsc-gdi.so usbdm-dsc-gdi-debug.so"
+   CF_GDI_TARGETS="libusbdm-gdi-cfv1.so libusbdm-gdi-cfvx.so libusbdm-gdi-cfv1-debug.so libusbdm-gdi-cfvx-debug.so"
+   HCS_GDI_TARGETS="libusbdm-gdi-hcs08.so libusbdm-gdi-rs08.so libusbdm-gdi-hcs08-debug.so libusbdm-gdi-rs08-debug.so"
+   S12Z_GDI_TARGETS="libusbdm-gdi-s12z.so libusbdm-gdi-s12z-debug.so"
+   ARM_GDI_TARGETS="libusbdm-gdi-arm.so libusbdm-gdi-arm-debug.so"
+   DSC_GDI_TARGETS="libusbdm-gdi-dsc.so libusbdm-gdi-dsc-debug.so"
 
    echo
    echo "Removing CFV1 & CFVx GDI files from '${CF_GDI_DIRECTORY}'"
@@ -222,13 +217,13 @@ uninstallCodewarriorInstance() {
    echo touch ${WIZARD_BASE_DIR}\*
    touch ${WIZARD_BASE_DIR}*
 
-   uninstallEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}"
+   removeEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}" ${CW_FEATURE_GROUP}
 }
 
 #======================================================
 #  Codewarrior Removal
 #======================================================
-uninstallCodewarrior() {
+removeCodewarrior() {
 
    echo 
    echo "Checking for Codewarrior directory"
@@ -237,7 +232,7 @@ uninstallCodewarrior() {
       echo -n "Looking for Codewarrior in '${CODEWARRIOR_DIR}'"
       if [[ -d ${CODEWARRIOR_DIR} ]]; then
          echo " - Found"
-         uninstallCodewarriorInstance ${CODEWARRIOR_DIR}
+         removeCodewarriorInstance ${CODEWARRIOR_DIR}
       else
          echo " - Not Found"
       fi
@@ -249,8 +244,9 @@ uninstallCodewarrior() {
 # USBDM Version
 #
 MAJOR=4
-MINOR=10
+MINOR=11
 VERSION=${MAJOR}.${MINOR}
+CP_OPTIONS=-p
 
 # Where to find files (relative to /)
 DUMMY_ROOT=""
@@ -266,18 +262,20 @@ else
 fi 
 
 USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
-USBDM_CDT_PLUGINS_DIR="${USBDM_SHARED_DIR}/CDT_Plugins"
-USBDM_CW_PLUGINS_DIR="${USBDM_SHARED_DIR}/CW_Plugins"
+USBDM_UPDATE_SITE="${USBDM_SHARED_DIR}/UpdateSite"
 USBDM_CW_LAUNCH_CONFIG_DIR="${USBDM_SHARED_DIR}/LaunchConfig"
 USBDM_CW_WIZARD_PATCH_DIR="${USBDM_SHARED_DIR}/WizardPatches"
+
+CDT_FEATURE_GROUP="net.sourceforge.usbdm.cdt.feature.feature.group"
+CW_FEATURE_GROUP="net.sourceforge.usbdm.cw.feature.feature.group"
 
 # System directories
 LIB_DIR="/usr/lib"
 BIN_DIR="/usr/bin"
 RULES_DIR="/etc/udev/rules.d"
 
-uninstallUSBHardware
-uninstallEclipse
-uninstallKDS
-uninstallCodewarrior
+removeUSBHardware
+removeEclipse
+removeKDS
+removeCodewarrior
 
diff --git a/PackageFiles/MiscellaneousLinux/DEBIAN/unTry b/PackageFiles/MiscellaneousLinux/DEBIAN/unTry
--- a/PackageFiles/MiscellaneousLinux/DEBIAN/unTry
+++ b/PackageFiles/MiscellaneousLinux/DEBIAN/unTry
@@ -2,27 +2,23 @@
 set -e
 
 #======================================================
-#  USB Hardware Installation
+#  USB Hardware Removal
 #======================================================
-installUSBHardware() {
+removeUSBHardware() {
 
    echo
-   echo "Copying rules file to ${RULES_DIR}"
-   echo "(Allows USBDM device to be accessed)"
+   echo "Removing rules file from ${RULES_DIR}"
    echo "=================================================================="
    rm -fv ${RULES_DIR}/*usbdm.rules
-   cp -fv $CP_OPTIONS ${USBDM_SHARED_DIR}/usbdm.rules ${RULES_DIR}/46-usbdm.rules
-   echo "chmod a+r      ${RULES_DIR}/46-usbdm.rules"
-   chmod a+r      ${RULES_DIR}/46-usbdm.rules
 }
 
 #======================================================
-#  Eclipse Plugin Installation
+#  Eclipse Plugin Removal
 #======================================================
 # $1 - Eclipse directory
 # $2 - Feature Group
 #
-installEclipsePlugins() {
+removeEclipsePlugins() {
 
    P2_APPLICATION="org.eclipse.equinox.p2.director"
 
@@ -30,20 +26,20 @@ installEclipsePlugins() {
    local FEATURE_GROUP="$2"
 
    echo 
-   echo "Installing Eclipse CDT plugins to ${ECLIPSE_DIR}"
+   echo "Removing Eclipse CDT plugins from ${ECLIPSE_DIR}"
    echo "=================================================================="
    for FILENAME in cwide eclipse; do
       if [[ -x "${ECLIPSE_DIR}/${FILENAME}" ]]; then
-         echo ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -repository file:/${USBDM_UPDATE_SITE} -installIU ${FEATURE_GROUP}
-         ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -repository file:/${USBDM_UPDATE_SITE} -installIU ${FEATURE_GROUP}
+         echo ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -uninstallIU ${FEATURE_GROUP}
+         ${ECLIPSE_DIR}/${FILENAME} -nosplash -application ${P2_APPLICATION} -uninstallIU ${FEATURE_GROUP} || true
       fi
    done
 }
 
 #======================================================
-#  Eclipse Installation
+#  Eclipse Removal
 #======================================================
-installEclipse() {
+removeEclipse() {
 
    local ECLIPSE_DIR_LIST="/usr/local/eclipse* /opt/eclipse* /usr/lib/eclipse*"
 
@@ -54,7 +50,7 @@ installEclipse() {
       echo -n "Looking for Eclipse in '${ECLIPSE_DIR}'"
       if [[ -d ${ECLIPSE_DIR} ]]; then
          echo " - Found"
-         installEclipsePlugins ${ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
+         removeEclipsePlugins ${ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
       else
         echo " - Not Found"
       fi
@@ -62,9 +58,9 @@ installEclipse() {
 }
 
 #======================================================
-#  KDS Instance Installation
+#  KDS Instance Removal
 #======================================================
-installKDSInstance() {
+removeKDSInstance() {
 
    local KDS_DIR="$1"
    local KDS_TOOLCHAIN_LIB_DIR="${KDS_DIR}/toolchain/arm-none-eabi/lib"
@@ -73,37 +69,35 @@ installKDSInstance() {
    local KDS_PR_XLKR_FILENAME="net.sourceforge.usbdm.cdt.arm.toolchain.c.compiler.xlkr"
    #local KDS_NANO_SPECS_FILENAME="nano.specs"
    
-   # Add USBDM plugins to eclipse
-   installEclipsePlugins ${KDS_ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
+   # Remove USBDM plugins to eclipse
+   removeEclipsePlugins ${KDS_ECLIPSE_DIR} ${CDT_FEATURE_GROUP}
 
    # Add Toolchain nano.specs files
    # KDS now used the OS GNU tools - not their own version
-   #local SOURCE="${USBDM_SHARED_DIR}/${KDS_NANO_SPECS_FILENAME}"
    #local DESTINATION="${KDS_TOOLCHAIN_LIB_DIR}/${KDS_NANO_SPECS_FILENAME}"
    
-   #echo Installing nano.specs files...
-   #if [[ -d ${KDS_TOOLCHAIN_LIB_DIR} ]]; then
-   #   ln -svf ${SOURCE} ${DESTINATION}
+   #echo Removing nano.specs files...
+   #if [[ -f ${DESTINATION} ]]; then
+   #   rm -fv ${DESTINATION}
    #else
-   #  echo " Toolchain directory '${KDS_TOOLCHAIN_LIB_DIR}' - Not Found"
+   #  echo " Specs file '${DESTINATION}' - Not Found"
    #fi
 
-   # Add PE files
-   local SOURCE="${USBDM_SHARED_DIR}/${KDS_PR_XLKR_FILENAME}"
+   # Remove PE files
    local DESTINATION="${KDS_PE_DIR}/${KDS_PR_XLKR_FILENAME}"
    
-   echo Installing PE files...
-   if [[ -d ${KDS_PE_DIR} ]]; then
-      ln -svf ${SOURCE} ${DESTINATION}
+   echo Removing PE files...
+   if [[ -f ${DESTINATION} ]]; then
+      rm -fv ${DESTINATION}
    else
-     echo " Processor Expert directory '${KDS_PE_DIR}' - Not Found"
+     echo " Processor Expert file '${DESTINATION}' - Not Found"
    fi
 }
 
 #======================================================
-#  KDS Installation
+#  KDS Removal
 #======================================================
-installKDS() {
+removeKDS() {
 
    local KDS_DIR_LIST="/usr/local/Freescale/KDS_* /opt/Freescale/KDS_*"
 
@@ -114,7 +108,7 @@ installKDS() {
       echo -n "Looking for Freescale KDS in '${KDS_DIR}'"
       if [[ -d ${KDS_DIR} ]]; then
          echo " - Found"
-         installKDSInstance ${KDS_DIR}
+         removeKDSInstance ${KDS_DIR}
       else
          echo " - Not Found"
       fi
@@ -122,9 +116,9 @@ installKDS() {
 }
 
 #======================================================
-#  Codewarrior Instance Installation
+#  Codewarrior Instance Removal
 #======================================================
-installCodewarriorInstance() {
+removeCodewarriorInstance() {
 
    local CODEWARRIOR_DIR="$1"
    local CODEWARRIOR_ECLIPSE_DIR="$1/eclipse"
@@ -153,90 +147,77 @@ installCodewarriorInstance() {
    DSC_GDI_TARGETS="libusbdm-gdi-dsc.so libusbdm-gdi-dsc-debug.so"
 
    echo
-   echo "Installing CFV1 & CFVx GDI files to '${CF_GDI_DIRECTORY}'"
+   echo "Removing CFV1 & CFVx GDI files from '${CF_GDI_DIRECTORY}'"
    echo "=================================================================="
    for FILENAME in ${CF_GDI_TARGETS}; do
-      echo "Linking ..."
-      local SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
       local DESTINATION="${CF_GDI_DIRECTORY}/${FILENAME}"
-      ln -svf ${SOURCE} ${DESTINATION}
+      rm -vf ${DESTINATION}
    done
 
    echo
-   echo "Installing RS08 & HCS08 GDI files from '${HCS_GDI_DIRECTORY}'"
+   echo "Removing RS08 & HCS08 GDI files from '${HCS_GDI_DIRECTORY}'"
    echo "=================================================================="
-   echo "Linking ..."
    for FILENAME in ${HCS_GDI_TARGETS}; do
-      local SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
       local DESTINATION="${HCS_GDI_DIRECTORY}/${FILENAME}"
-      ln -svf ${SOURCE} ${DESTINATION}
+      rm -vf ${DESTINATION}
    done
 
    echo
-   echo "Installing S12Z GDI files from '${S12Z_GDI_DIRECTORY}'"
+   echo "Removing S12Z GDI files from '${S12Z_GDI_DIRECTORY}'"
    echo "=================================================================="
-   echo "Linking ..."
    for FILENAME in ${S12Z_GDI_TARGETS}; do
-      local SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
       local DESTINATION="${S12Z_GDI_DIRECTORY}/${FILENAME}"
-      ln -svf ${SOURCE} ${DESTINATION}
+      rm -vf ${DESTINATION}
    done
 
    echo
-   echo "Installing Kinetis GDI files from '${ARM_GDI_DIRECTORY}'"
+   echo "Removing Kinetis GDI files from '${ARM_GDI_DIRECTORY}'"
    echo "=================================================================="
-   echo "Linking ..."
    for FILENAME in ${ARM_GDI_TARGETS}; do
-      local SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
       local DESTINATION="${ARM_GDI_DIRECTORY}/${FILENAME}"
-      ln -svf ${SOURCE} ${DESTINATION}
+      rm -vf ${DESTINATION}
    done
 
    echo
-   echo "Installing DSC GDI files from '${DSC_GDI_DIRECTORY}'"
+   echo "Removing DSC GDI files from '${DSC_GDI_DIRECTORY}'"
    echo "=================================================================="
-   echo "Linking ..."
    for FILENAME in ${DSC_GDI_TARGETS}; do
-      local SOURCE="${USBDM_LIB_DIR}/lib${FILENAME}.${VERSION}"
       local DESTINATION="${DSC_GDI_DIRECTORY}/${FILENAME}"
-      ln -svf ${SOURCE} ${DESTINATION}
+      rm -vf ${DESTINATION}
    done
 
    echo
-   echo "Installing Codewarrior Project Wizard Files for USBDM"
+   echo "Removing Codewarrior Project Wizard Files for USBDM"
    echo "=================================================================="
-   echo "Installing launch settings"
-   echo "Linking ..."
-   ln -svf "${USBDM_CW_LAUNCH_CONFIG_DIR}/"*".xml" ${WIZARD_DIRECTORY}/launch_config
+   echo "Removing launch settings"
+   rm -vf ${WIZARD_DIRECTORY}/launch_config/usbdm*
 
    echo
-   echo "Patching New Project Wizard"
+   echo "Unpatching New Project Wizard"
    CODEWARRIOR_PATCH_NEW_WIZARD="PatchNewWizardPlugin_V10.2.xml"
-   WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_NEW_WIZARD}
    WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.projectwizard_"  
-   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml ${WIZARD_PATCH_FILE}
+   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
    echo touch ${WIZARD_BASE_DIR}\*
    touch ${WIZARD_BASE_DIR}*
 
    echo
-   echo "Patching Change Project Wizard"
-   CODEWARRIOR_PATCH_CHANGE_WIZARD="PatchChangeWizardPlugin_V10.2.xml"
+   echo "Unpatching Change Project Wizard"
    WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_CHANGE_WIZARD}
    WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.changewizard_"  
-   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml ${WIZARD_PATCH_FILE}
+   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
 
    echo 
    echo "Refreshing Eclipse"
    echo touch ${WIZARD_BASE_DIR}\*
    touch ${WIZARD_BASE_DIR}*
 
-   installEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}" ${CW_FEATURE_GROUP}
+   removeEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}" ${CW_FEATURE_GROUP}
 }
 
 #======================================================
-#  Codewarrior Installation
+#  Codewarrior Removal
 #======================================================
-installCodewarrior() {
+removeCodewarrior() {
 
    echo 
    echo "Checking for Codewarrior directory"
@@ -245,24 +226,12 @@ installCodewarrior() {
       echo -n "Looking for Codewarrior in '${CODEWARRIOR_DIR}'"
       if [[ -d ${CODEWARRIOR_DIR} ]]; then
          echo " - Found"
-         installCodewarriorInstance ${CODEWARRIOR_DIR}
+         removeCodewarriorInstance ${CODEWARRIOR_DIR}
       else
          echo " - Not Found"
       fi
    done
 
-}
-
-#======================================================
-#  Library Refresh
-#======================================================
-libraryUpdate() {
-   if [ "$1" != "configure" ]; then
-      return
-   fi 
-
-   echo ldconfig ${USBDM_LIB_DIR}
-   ldconfig ${USBDM_LIB_DIR}
 }
 
 #================================
@@ -299,9 +268,8 @@ LIB_DIR="/usr/lib"
 BIN_DIR="/usr/bin"
 RULES_DIR="/etc/udev/rules.d"
 
-installUSBHardware
-installEclipse
-installKDS
-installCodewarrior
-#libraryUpdate $1
+removeUSBHardware
+removeEclipse
+removeKDS
+removeCodewarrior
 
