V4.12.1.270 - Update build scripts

diff --git a/CreateDebFile b/CreateDebFile
--- a/CreateDebFile
+++ b/CreateDebFile
@@ -14,9 +14,20 @@ ARCH=`uname -m`
 clear
 
 SOURCE_DIRECTORY="$(dirname $(readlink -f $0))"
-echo "SOURCE_DIRECTORY=${SOURCE_DIRECTORY}"
+echo "Building DEB file in ${SOURCE_DIRECTORY}"
 
 DATE=`date +"%Y%m%d%H%M%S"`
+
+pausing() {
+   x=5
+   echo -n Pausing ...
+   while [ $x -gt 0 ];  do
+      sleep 1s
+      echo -n " $x"
+      x=$(( $x - 1 ))
+   done
+   echo 
+}
 
 #======================================================
 # Create ARCH dependent DEB file
@@ -185,6 +196,19 @@ echo "Building `getconf LONG_BIT` version"
 echo "========================================="
 makeDebFile `getconf LONG_BIT`
 
+if [ $? -eq 0 ]
+then
+  echo "makeDebFile successfully completed"
+  pausing
+  exit 0
+else
+  echo "makeDebFile failed" >&2
+  read -p "Press any key to continue... " -n1 -s  exit 1
+  exit 1
+fi
+
+
+
 # Build for i386 on x86_64 platform
 #if [ `getconf LONG_BIT` != 32 ]; then
 #   echo "========================================="
@@ -192,8 +216,4 @@ makeDebFile `getconf LONG_BIT`
 #   echo "========================================="
 #   makeDebFile 32
 #fi
-
-echo
-echo "Finished Buid"
-read -p "Press enter"
 
diff --git a/MakeAll b/MakeAll
--- a/MakeAll
+++ b/MakeAll
@@ -2,6 +2,8 @@
 
 # Build with native BITNESS
 
+clear
+
 HOME_DIR="$(dirname $(readlink -f $0))"
 echo "Building in ${HOME_DIR}"
 pushd ${HOME_DIR}
@@ -9,12 +11,28 @@ pushd ${HOME_DIR}
 OS=linux
 export OS
 
-clear
+pausing() {
+   x=5
+   echo -n Pausing ...
+   while [ $x -gt 0 ];  do
+      sleep 1s
+      echo -n " $x"
+      x=$(( $x - 1 ))
+   done
+   echo 
+}
 
 # Do 64-bit builds
 echo make -f Makefile-x64.mk all BITNESS=64
 make -f Makefile-x64.mk all BITNESS=64
 
-echo
-echo "Finished Buid"
-read -p "Press enter"
+if [ $? -eq 0 ]
+then
+  echo "Make successfully completed"
+  pausing
+  exit 0
+else
+  echo "Make failed" >&2
+  read -p "Press any key to continue... " -n1 -s  exit 1
+  exit 1
+fi
diff --git a/Update b/Update
--- a/Update
+++ b/Update
@@ -13,6 +13,20 @@ ARCH=`uname -m`
 
 BITNESS=`getconf LONG_BIT`
 
+SOURCE_DIRECTORY="$(dirname $(readlink -f $0))"
+echo "Updating from file in ${SOURCE_DIRECTORY}"
+
+pausing() {
+   x=5
+   echo -n Pausing ...
+   while [ $x -gt 0 ];  do
+      sleep 1s
+      echo -n " $x"
+      x=$(( $x - 1 ))
+   done
+   echo 
+}
+
 # Where to construct the install tree
 PACKAGE_FILE="../usbdm_${VERSION}-${DEBIAN_VERSION}-${ARCH}.deb"
 
@@ -22,3 +36,13 @@ sudo apt-get -y remove usbdm
 echo "Installing ${PACKAGE_FILE}"
 sudo dpkg -i ${PACKAGE_FILE}
 
+if [ $? -eq 0 ]
+then
+  echo "Finished updating installation"
+  pausing
+  exit 0
+else
+  echo "Updating failed" >&2
+  read -p "Press any key to continue... " -n1 -s  exit 1
+  exit 1
+fi
